# Generated by Django 4.2.6 on 2023-10-26 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
