# Generated by Django 4.2.6 on 2023-10-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_item_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='stock',
            table='stock',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
