# Generated by Django 4.2.6 on 2023-11-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_cart_table_alter_item_table_alter_order_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='Em estoque', max_length=200),
        ),
    ]
