# Generated by Django 4.2.6 on 2023-11-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='Sem Estoque', max_length=200),
        ),
    ]
